spring:
  datasource:
    url: jdbc:h2:file:./mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        ddl-auto: none
  flyway:
    url: jdbc:h2:file:./mydb
    user: sa
    password: password

server:
  servlet:
    context-path: /api

logging:
  level:
    '[br.com.zup]': debug
